# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df514e7f5511477f3c02f2d44291a64233d9ef9e3fe93c2780beff17555ba802ecf3ed09479db217af66da530e86f8d8d17549f83f45cf4f5c358e366c53f4d6

test:
  secret_key_base: 4086de761146fa4cbdd6de7f66ef2458be592b79cac4389f54e4fb16d518af62dccbb482a6fa9c678b6e7984a9df802e24dec8efc02003e121ee044000570c8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
